MERGE INTO CM_PRETENZ_ALL cp
  using
    (select c0.ACCT_ID, c0.SERVICE_ADDRESS, c0.TYPE_OO
    from CASH_CCB_TABLE_Q0 c0) S
     on (s.ACCT_ID = cp.PERSONAL_COUNT)
        WHEN MATCHED THEN UPDATE SET cp.SERVICE_ADDRESS = s.SERVICE_ADDRESS, cp.TYPE_OO_1 = s.TYPE_OO